[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images"
  query = {url = ":url", w = ":width", q = ":quality"}
  status = 200

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images"
  query = {url = ":url", w = ":width", q = ":quality"}
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs" 